php:
  - 5.3
before_install:
  - git submodule update --init --recursive
  - BRANCH=`git branch 2>/dev/null | grep "^ " | cut -c3-`
  - git clone git://github.com/novius-os/ci.git
  - cd ci
  - git checkout $BRANCH
  - cd ..
before_script:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - mysql -e 'CREATE DATABASE novius_os DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - phpcs -p -s --standard=ci/phpcs/ruleset.xml ./
