services:
  - mysql
notifications:
  email:
    recipients:
      - team@novius-os.org
    on_success: change
    on_failure: always
before_install:
  - BRANCH=$(echo `git for-each-ref --format='%(objectname) %(refname:short)' refs/heads | awk "/^$(git rev-parse HEAD)/ {print \$2}"` | cut -d" " -f2);
  - git submodule update --init --recursive
  - git clone git://github.com/novius-os/ci.git
  - cd ci
  - echo $BRANCH
  - git checkout $BRANCH
  - cd ..
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y --force-yes apache2 php5 libapache2-mod-php5 php5-mysql php-pear
  - sudo a2enmod rewrite
  - cat ci/virtualhost | sed -e "s,PATH,`pwd`/public,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 reload
  - sudo sh -c 'echo "127.0.0.1 novius-os" >> /etc/hosts'
before_script:
  - sudo chmod +x ci/scripts/travis.sh
script:
  - cd ci/scripts
  - ./travis.sh
