php:
  - 5.3
before_install:
  - git submodule update --init --recursive
  - git clone git://github.com/novius-os/ci.git
  - sudo apt-get install apache2 php5 mysql-server libapache2-mod-php5 php5-mysql
  - sudo a2enmod rewrite
  - sudo sh -c 'echo "<VirtualHost *:80>" >> /etc/apache2/sites-available/novius-os'
  - sudo sh -c 'echo " DocumentRoot `pwd`/public" >> /etc/apache2/sites-available/novius-os'
  - sudo sh -c 'echo " ServerName novius-os" >> /etc/apache2/sites-available/novius-os'
  - sudo sh -c 'echo " <Directory `pwd`/public>" >> /etc/apache2/sites-available/novius-os'
  - sudo sh -c 'echo " AllowOverride All" >> /etc/apache2/sites-available/novius-os'
  - sudo sh -c 'echo " Options FollowSymLinks" >> /etc/apache2/sites-available/novius-os'
  - sudo sh -c 'echo " </Directory>" >> /etc/apache2/sites-available/novius-os'
  - sudo sh -c 'echo "</VirtualHost>" >> /etc/apache2/sites-available/novius-os'
  - sudo a2ensite novius-os
  - sudo service apache2 reload
  - sudo sh -c 'echo "127.0.0.1 novius-os" >> /etc/hosts'
before_script:
  - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "DISPLAY=:99.0 ./ci/casperjs/bin/casperjs test --direct --log-level=debug ./ci/tests/"

